---
- name: Copy named conf file
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0660
  notify: restart named

- name: Copy rndc.key file
  template:
    src: rndc.key.j2
    dest: /etc/rndc.key
    owner: root
    group: named
    mode: 0660
  notify: restart named

- name: Ensure named directory exists
  file:
    path: /var/named
    state: directory
    owner: root
    group: named
    mode: 0750

#- name: Copy named conf local file
#  template:
#    src: named.conf.local.j2
#    dest: /var/named/named.conf.local
#    owner: root
#    group: named
#    mode: 0640
#  notify: restart named

- name: Make zones Directory
  file:
    path: /var/named/zones
    state: directory
    owner: root
    group: named
    mode: 0750
#
#- name: Copy reverse file
#  template:
#    src: db.reverse.j2
#    dest: "/var/named/{{ item.name | ipaddr('revdns') }}.db"
#    owner: root
#    group: named
#    mode: 0640
#  notify: restart named
#  loop: isc_bind_server_subnets
#
#
#- name: Copy forward file
#  template:
#    src: db.forward.j2
#    dest: "/var/named/zones/{{ item }}.db"
#    owner: root
#    group: named
#    mode: 0640
#  notify: restart named
#  loop: isc_bind_server_domains

- name: Enable and Restart named service
  service:
    name: "{{ isc_bind_server_service }}"
    state: restarted
    enable: yes
